import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b border-zinc-200 bg-white/80 backdrop-blur dark:border-zinc-900 dark:bg-black/60">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4 sm:px-10">
            <div className="flex items-center gap-2">
              <span className="inline-block h-2.5 w-2.5 rounded-full bg-zinc-900 dark:bg-zinc-100" />
              <span className="text-sm font-semibold tracking-tight">Proget</span>
            </div>
            <nav className="hidden gap-6 text-sm text-zinc-600 dark:text-zinc-400 sm:flex">
              <a href="/" className="hover:text-zinc-900 dark:hover:text-zinc-200">Home</a>
              <a href="https://nextjs.org/docs" target="_blank" rel="noopener noreferrer" className="hover:text-zinc-900 dark:hover:text-zinc-200">Docs</a>
              <a href="https://vercel.com" target="_blank" rel="noopener noreferrer" className="hover:text-zinc-900 dark:hover:text-zinc-200">Deploy</a>
            </nav>
          </div>
        </header>
        {children}
        <footer className="mt-auto border-t border-zinc-200 bg-white/60 py-6 text-center text-sm text-zinc-600 dark:border-zinc-900 dark:bg-black/40 dark:text-zinc-400">
          <div className="mx-auto max-w-5xl px-6 sm:px-10">
            Built with Next.js • Styled with Tailwind
          </div>
        </footer>
      </body>
    </html>
  );
}
